// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkiukoeankeojpntfhvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJraXVrb2Vhbmtlb2pwbnRmaHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTI5MDQsImV4cCI6MjA2MDkyODkwNH0.-V81gAim0WSdyXAnhx4Fio6PuWwd2WM7fkttAdrqBV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);